# """
# Django settings for geomap_stores project.
# Generated by 'django-admin startproject' using Django 5.2.8.
# """

# from pathlib import Path
# import os
# # os.environ["PROJ_LIB"] = r"C:\OSGeo4W\share\proj"

# import os

# # --- OSGeo4W Configuration (Windows Fix) ---
# OSGEO4W = r"C:\OSGeo4W"
# os.environ["OSGEO4W_ROOT"] = OSGEO4W
# os.environ["GDAL_DATA"] = fr"{OSGEO4W}\share\gdal"
# os.environ["PROJ_LIB"] = fr"{OSGEO4W}\share\proj"

# # Add OSGeo4W bin to PATH (very important)
# os.environ["PATH"] = fr"{OSGEO4W}\bin;" + os.environ["PATH"]

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # -----------------------
# # Basic Settings
# # -----------------------

# SECRET_KEY = 'django-insecure-7kry6*$#m2@7wit_=xj-c08lmr68-6@x6=0wqz+-4!#bri*zhe'
# DEBUG = True
# ALLOWED_HOSTS = []


# # -----------------------
# # Application Definition
# # -----------------------

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',

#     # GeoDjango
#     'django.contrib.gis',

#     # Third-party
#     'crispy_forms',

#     # Local apps
#     'shops',
# ]


# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]


# ROOT_URLCONF = 'geomap_stores.urls'


# # -----------------------
# # Templates
# # -----------------------

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, "templates")],  # <-- custom templates folder
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]


# WSGI_APPLICATION = 'geomap_stores.wsgi.application'


# # -----------------------
# # Database (PostGIS)
# # -----------------------

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'NAME': 'geomap_stores_db',
#         'USER': 'postgres',
#         'PASSWORD': 'Pass@123',   # <-- replace with your actual password
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }



# # -----------------------
# # Password Validation
# # -----------------------

# AUTH_PASSWORD_VALIDATORS = [
#     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
# ]


# # -----------------------
# # Internationalization
# # -----------------------

# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'Asia/Kolkata'
# USE_I18N = True
# USE_TZ = True


# # -----------------------
# # Static Files
# # -----------------------

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]


# # -----------------------
# # Crispy Forms
# # -----------------------

# CRISPY_TEMPLATE_PACK = "bootstrap4"


# # -----------------------
# # Default Primary Key
# # -----------------------

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# # GDAL / GEOS paths for GeoDjango on Windows (update filenames if different)
# GEOS_LIBRARY_PATH = r"C:\OSGeo4W\bin\geos_c.dll"
# GDAL_LIBRARY_PATH = r"C:\OSGeo4W\bin\gdal309.dll"


"""
Django settings for geomap_stores project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os

# --- OSGeo4W Configuration (Windows Fix) ---
OSGEO4W = r"C:\OSGeo4W"
os.environ["OSGEO4W_ROOT"] = OSGEO4W
os.environ["GDAL_DATA"] = fr"{OSGEO4W}\share\gdal"
os.environ["PROJ_LIB"] = fr"{OSGEO4W}\share\proj"

# Add OSGeo4W bin to PATH (VERY important)
os.environ["PATH"] = fr"{OSGEO4W}\bin;" + os.environ["PATH"]

# Correct GDAL & GEOS DLLs
GEOS_LIBRARY_PATH = r"C:\OSGeo4W\bin\geos_c.dll"
GDAL_LIBRARY_PATH = r"C:\OSGeo4W\bin\gdal311.dll"   # ✔ FIXED


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# -----------------------
# Basic Settings
# -----------------------

SECRET_KEY = 'django-insecure-7kry6*$#m2@7wit_=xj-c08lmr68-6@x6=0wqz+-4!#bri*zhe'
DEBUG = True
ALLOWED_HOSTS = []


# -----------------------
# Application Definition
# -----------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # GeoDjango
    'django.contrib.gis',

    # Third-party
    'crispy_forms',

    # Local apps
    'shops',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'geomap_stores.urls'


# -----------------------
# Templates
# -----------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'geomap_stores.wsgi.application'


# -----------------------
# Database (PostGIS)
# -----------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'geomap_stores_db',
        'USER': 'postgres',
        'PASSWORD': 'Pass@123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# -----------------------
# Password Validation
# -----------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# -----------------------
# Internationalization
# -----------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True


# -----------------------
# Static Files
# -----------------------

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# -----------------------
# Crispy Forms
# -----------------------

CRISPY_TEMPLATE_PACK = "bootstrap4"


# -----------------------
# Default Primary Key
# -----------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
